spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:postgres@localhost:5432/demo_reactive
    pool:
      enabled: true
      initial-size: 5
      max-size: 10

grpc:
  server:
    port: 9090
    security:
      enabled: true
      certificate-chain: classpath:certificates/server.crt
      private-key: classpath:/certificates/server.key

logging:
  level:
    org.springframework.r2dbc: DEBUG
