name: Push Image to Container Registry

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1
  ECR_DEPLOY_ROLE_ARN: arn:aws:iam::870575329641:role/github-actions-role
  REPOSITORY: 870575329641.dkr.ecr.ap-southeast-1.amazonaws.com/demo-reactive

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/aws-actions/configure-aws-credentials#OIDC
      - name: Configure AWS credentials from ecr deployer account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ env.ECR_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean package

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$env.REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$env.ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Image digest
        run: echo ${{ steps.build.outputs.digest }}
